### PR TITLE
DEV: Fix `redis` gem 4.6.0 deprecations

### PR DESCRIPTION
**Pull request by CvX**

### CODE REVIEW

**Review by OsamaSayegh — APPROVED** [review]

**Review by udan11 — APPROVED** [review]

**Comment by OsamaSayegh** [comment]
Should we merge this @CvX?

**Comment by CvX** [comment]
Hm, not yet. Converting to a draft as I'll need to make core changes first.

**Comment by nlalonde** [comment]
Any update on this?

**Comment by tgxworld** [comment]
Superseded by https://github.com/discourse/logster/pull/159

**Pull request closed without merging**
