### PR TITLE
FEATURE: Linkify backtrace lines to github

### PR DESCRIPTION
**Pull request by OsamaSayegh**
This PR adds a new feature that allows Logster to make each backtrace line link to the correct file and line on Github. This PR also truncates backtrace lines from gems to reduce noise (you can click on ... next to each line to expand).

The way this works is you need to provide Logster with an array of hashes where each hash represents a directory/repository path on the file system and a Github link of the repository.

For example if you're using Logster with a Rails app, your Logster configuration for this feature may look like this:

```ruby
Logster.config.project_directories = [
  { path: Rails.root.to_s, url: "https://github.com/<your_org>/<your_repo>" }
]
```
Additionally, you can add a `main_app: true` key to the hash to indicate that Logster should use the current value of the `application_version` config when generating Github links. That way the Github links will point to the exact version of your app when the error occurred. If this key is not given in the hash, Logster will use the `master` branch.

Screenshot:

image

### CODE REVIEW

**Comment by SamSaffron** [comment]
Can we make the link a bit more subtle? maybe a simple icon? 

Also I wonder if we should also allow for a very simple local file viewer? Then you can click on any file at all and show it if it is available on local?

**Comment by OsamaSayegh** [comment]
Are you thinking something like this?

image

Or maybe put the icon to the left?

image

Yeah I think it makes sense to have local file viewer as a fallback option that can be turned on or off. If we can't figure out the Github link, we fallback to showing the file locally if it's turned on.

**Comment by SamSaffron** [comment]
I like the link to the right, also maybe the `...` is just too much noise and we skip it?

**Comment by OsamaSayegh** [comment]
Ok, here is how it looks now:

image

If this looks good now, I'd like to merge this and make a separate PR for local file viewer. Does this sound good?

**Comment by SamSaffron** [comment]
Looks good to me now! Yeah lets try this out!

**Pull request merged**
