### PR TITLE
Remove Redis 4.2 warnings

### PR DESCRIPTION
**Pull request by bf4**
Apps on Redis 4.2 and up will see a warning due to redis/redis-rb@3257527

Same as https://github.com/MiniProfiler/rack-mini-profiler/pull/450

### CODE REVIEW

**Comment by SamSaffron** [comment]
Nice change, thanks @bf4

**Comment by bf4** [comment]
Thanks @SamSaffron Any idea when you might plan a (patch) release? I'm getting a lot of warning in our logs and I think I'm gonna point our Gemfile to master but I don't want to the get off the 'using released versions' train

**Comment by SamSaffron** [comment]
A version is in the oven :)

**Comment by bf4** [comment]
Version in the oven gonna watch in rise

**Pull request merged**
